# Generated by Django 5.2.8 on 2025-11-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pemeriksaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode', models.CharField(default='Cash', max_length=50)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pemeriksaan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pemeriksaan.pemeriksaan')),
            ],
        ),
    ]
