# Generated by Django 5.2.8 on 2025-11-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(max_length=100)),
                ('nama_dokter', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('keluhan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.TextField()),
                ('tindakan', models.TextField()),
                ('resep_obat', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemeriksaan.jadwalpemeriksaan')),
            ],
        ),
    ]
