# Generated by Django 5.2.8 on 2025-11-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('fasilitas', '0001_initial'),
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hewan', models.CharField(max_length=50)),
                ('keluhan', models.TextField()),
                ('diagnosa', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('dokter', models.ForeignKey(limit_choices_to={'jabatan': 'dokter'}, on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
                ('tindakan', models.ManyToManyField(to='fasilitas.fasilitas')),
            ],
        ),
    ]
