# Generated by Django 5.2.8 on 2025-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('obat', 'Obat'), ('perawatan', 'Perawatan'), ('penginapan', 'Rawat Inap'), ('info', 'Informasi')], max_length=20)),
                ('harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
