# Generated by Django 5.2.8 on 2025-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(choices=[('dokter', 'Dokter'), ('perawat', 'Perawat'), ('resepsionis', 'Resepsionis'), ('cleaning', 'Cleaning Service')], max_length=15)),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
    ]
